"""change field 'price' for model 'Dish'

Revision ID: f7443303b4c9
Revises: bff4df20397e
Create Date: 2024-01-22 15:58:52.656714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7443303b4c9"
down_revision: Union[str, None] = "bff4df20397e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dishes",
        "price",
        existing_type=sa.REAL(),
        type_=sa.DECIMAL(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dishes",
        "price",
        existing_type=sa.DECIMAL(precision=10, scale=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
