"""create dish_discount

Revision ID: 68f963649577
Revises: f7443303b4c9
Create Date: 2024-02-13 23:13:34.841825

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68f963649577"
down_revision: Union[str, None] = "f7443303b4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dishes",
        sa.Column("dish_discount", sa.DECIMAL(precision=4, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dishes", "dish_discount")
    # ### end Alembic commands ###
