"""Upgrade dish and submenu tables

Revision ID: 3db54ec77569
Revises: a08a085d56ee
Create Date: 2024-01-21 16:39:37.439405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3db54ec77569"
down_revision: Union[str, None] = "a08a085d56ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("submenu_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "dishes",
        "price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "dishes", ["id"])
    op.create_foreign_key(None, "dishes", "submenus", ["submenu_id"], ["id"])
    op.create_unique_constraint(None, "menus", ["id"])
    op.add_column("submenus", sa.Column("menu_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "submenus", ["id"])
    op.create_foreign_key(None, "submenus", "menus", ["menu_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "submenus", type_="foreignkey")
    op.drop_constraint(None, "submenus", type_="unique")
    op.drop_column("submenus", "menu_id")
    op.drop_constraint(None, "menus", type_="unique")
    op.drop_constraint(None, "dishes", type_="foreignkey")
    op.drop_constraint(None, "dishes", type_="unique")
    op.alter_column(
        "dishes",
        "price",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("dishes", "submenu_id")
    # ### end Alembic commands ###
